'use strict';
const $=id=>document.getElementById(id);
const duration=15000;
const lines=[{at:0,who:'Felipe',text:'Achei o mapa da nossa próxima aventura!',f:1,l:1},{at:3800,who:'Laís',text:'Você sabe o caminho… ou vai perguntar ao mapa?',f:5,l:2},{at:7600,who:'Felipe',text:'Com você, até me perder vale a pena.',f:2,l:0},{at:11200,who:'Laís',text:'Então vem. Mas eu fico com o mapa!',f:3,l:3}];
let elapsed=0,playing=false,last=0,frame=0,current=-1,audio=null,music=false,noteAt=0,noteIndex=0,voices=[];
const melody=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46,659.25,783.99,1046.5,783.99,587.33,659.25,523.25,0];
function pose(id,n){$(id).style.backgroundPosition=`${(n%3)*50}% ${Math.floor(n/3)*100}%`;}
function stopNotes(){voices.forEach(v=>{try{v.stop()}catch{}});voices=[];}
function note(){if(!music||!playing||!audio||audio.state!=='running')return;const now=audio.currentTime;if(now<noteAt)return;noteAt=now+.30;const frequency=melody[noteIndex++%melody.length];if(!frequency)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.045,now+.015);gain.gain.exponentialRampToValueAtTime(.001,now+.27);osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+.29);voices.push(osc);osc.onended=()=>{voices=voices.filter(v=>v!==osc);osc.disconnect();gain.disconnect();};}
async function enableAudio(){try{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return false;audio ||= new Context();await audio.resume();return audio.state==='running';}catch{return false;}}
function render(){const seconds=Math.min(15,Math.floor(elapsed/1000));$('clock').textContent=`0:${String(seconds).padStart(2,'0')} / 0:15`;$('progress').style.width=`${elapsed/duration*100}%`;document.querySelector('.progress').setAttribute('aria-valuenow',seconds);let i=lines.findLastIndex(l=>elapsed>=l.at);if(i!==current){current=i;const line=lines[i];$('speaker').textContent=line.who;$('line').textContent=line.text;$('speech').dataset.who=line.who;pose('felipe',line.f);pose('lais',line.l);$('scene').classList.toggle('depart',i===3);}}
function tick(now){if(!playing)return;elapsed=Math.min(duration,elapsed+Math.min(now-last,100));last=now;render();note();if(elapsed>=duration){playing=false;$('ending').hidden=false;$('speech').hidden=true;$('pause').disabled=true;$('scene').classList.remove('depart');stopNotes();return;}frame=requestAnimationFrame(tick);}
function start(){cancelAnimationFrame(frame);stopNotes();elapsed=0;current=-1;noteIndex=0;noteAt=0;playing=true;$('cover').hidden=true;$('ending').hidden=true;$('speech').hidden=false;$('pause').disabled=false;$('pause').innerHTML='Ⅱ <span>Pausar</span>';$('pause').setAttribute('aria-label','Pausar animação');$('scene').classList.remove('paused','depart');render();last=performance.now();frame=requestAnimationFrame(tick);if(music)enableAudio();}
function pause(){if(elapsed>=duration||!$('cover').hidden)return;playing=!playing;$('scene').classList.toggle('paused',!playing);$('pause').innerHTML=playing?'Ⅱ <span>Pausar</span>':'▶ <span>Continuar</span>';$('pause').setAttribute('aria-label',playing?'Pausar animação':'Continuar animação');if(playing){last=performance.now();frame=requestAnimationFrame(tick);if(music)enableAudio();}else{cancelAnimationFrame(frame);stopNotes();}}
$('start').onclick=start;$('replay').onclick=start;$('replay-end').onclick=start;$('pause').onclick=pause;
$('sound').onclick=async()=>{if(!music){music=await enableAudio();}else{music=false;stopNotes();}$('sound').setAttribute('aria-pressed',String(music));$('sound').innerHTML=`♫ <span>${music?'Som ligado':'Som desligado'}</span>`;};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause();});
pose('felipe',0);pose('lais',0);
